set nocompatible

execute pathogen#infect()

filetype plugin indent on

syntax on
colorscheme base16-tomorrow

set nomodeline
set wildmode=longest,list
set shiftround
set hlsearch highlight=l:Visual
set ignorecase
set smartcase
set scrolloff=4

nnoremap <silent> <C-L> <C-L>:nohlsearch<CR>
