set nocompatible

call pathogen#infect()

filetype plugin indent on

syntax on
colorscheme railscasts

set nomodeline
set wildmode=longest,list
set shiftround
set hlsearch highlight=l:Visual
set scrolloff=4

nnoremap <silent> <C-L> <C-L>:nohlsearch<CR>

let g:ctrlp_dotfiles = 0
let g:ctrlp_by_filename = 1

autocmd FileType ruby setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
