post_install() {
  getent group git &>/dev/null || groupadd -r git &>/dev/null
  getent passwd git &>/dev/null || useradd -r -g git -d /srv/gitosis -s /bin/sh git &>/dev/null
  mkdir -p -m 0700 /srv/gitosis
  chown git:git /srv/gitosis
}

post_upgrade() {
  post_install $1
}

post_remove() {
  getent passwd git &>/dev/null && userdel git &> /dev/null
  getent group git &>/dev/null && groupdel git &> /dev/null
}
